import "./globals.css";
import type { Metadata } from "next";
import React from "react";
import Providers from "@/providers/Providers";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-main">
        <Providers>
          <div className="flex min-h-screen w-screen flex-col gap-3 bg-gradient-to-r from-cyan-500 to-blue-500">
            <Navbar />
            <div className="bg-transparent h-[68px]" />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
