import "./globals.css";
import type { Metadata } from "next";
import React from "react";
import Providers from "@/providers/Providers";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-main min-h-screen w-screen overflow-x-hidden text-foreground">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
